import { assert, fakeCanvas } from "./helpers.mjs";
globalThis.requestAnimationFrame = () => 1; globalThis.cancelAnimationFrame = () => {};
const { SnakeGame, SIZE } = await import('../scripts/games/snake.js');
let last; const g = new SnakeGame({ board: fakeCanvas() }, s => last = s);
assert(g.state === 'idle' && !g.handleKey('ArrowUp'), 'idle until Enter');
g.handleKey('Enter'); assert(g.state === 'playing' && last.length === 3 && last.score === 0, 'Enter starts with length 3');
const head = () => g.snake[0].join();
g.food = [15, 10]; const h0 = g.snake[0]; g.step(); assert(g.snake[0][0] === h0[0] + 1, 'moves right by default');
g.handleKey('ArrowLeft'); g.step(); assert(g.dir[0] === 1, 'cannot reverse into itself');
g.handleKey('ArrowUp'); g.handleKey('ArrowLeft'); g.step(); g.step();
assert(g.dir[0] === -1 && g.dir[1] === 0, 'quick Up+Left are both queued (U-turn over two steps)');
g.start(); const [hx, hy] = g.snake[0]; g.food = [hx + 1, hy]; g.step();
assert(g.snake.length === 4 && g.score === 10 && last.length === 4, 'eating food grows and scores 10');
assert(g.food && !g.snake.some(([x, y]) => x === g.food[0] && y === g.food[1]), 'new food not on the snake');
for (let i = 0; i < 4; i++) { const [x, y] = g.snake[0]; g.food = [x + 1, y]; g.step(); }
assert(g.level === 2 && g.score === 50, `level 2 after 5 foods (score ${g.score})`);
const [x2, y2] = g.snake[0]; g.food = [x2 + 1, y2]; g.step();
assert(g.score === 70, 'food worth 10 x level');
assert(g.stepInterval < 140, 'speeds up with level');
g.handleKey('KeyW'); g.step(); assert(g.dir[1] === -1, 'WASD steers');
g.start(); g.food = [0, 0]; for (let i = 0; i < SIZE; i++) g.step();
assert(g.state === 'over' && last.state === 'over', 'hitting the wall ends the game');
const best = g.best; g.handleKey('Enter'); assert(g.score === 0 && g.best === best && g.state === 'playing', 'restart keeps best');
g.snake = [[5,5],[6,5],[6,6],[5,6],[4,6]]; g.dir = [0,1]; g.turns = []; g.food = [0,0]; g.step();
assert(g.state === 'over', 'running into own body ends the game');
g.start(); g.snake = [[5,5],[5,6],[6,6],[6,5]]; g.dir = [1,0]; g.turns = []; g.food = [0,0]; g.step();
assert(g.state === 'playing', 'moving into the cell the tail is leaving is allowed');
g.handleKey('KeyP'); assert(g.state === 'paused' && g.handleKey('ArrowUp') === false, 'pause blocks steering');
g.handleKey('Escape'); assert(g.state === 'playing', 'Esc resumes');
